### ISSUE TITLE
Segmentation Fault error on posti_preparerecordpoints

### ISSUE THREAD

**Issue by dfdeabreu** [flexi-framework/flexi#8] opened 2021-03-04 14:41 UTC
Flexi team,
I'm facing some difficulties trying to run the posti_preparerecordpoints. I have a mesh, that was generated with GMSH and then converted with HOPR, that is running with Flexi code. I'm trying to create some recordpoints for data post-processing. Once I was able to create RPSet file, however nowadays it is no longer possible. The error that is occurring is Segmentation Fault due to invalid memory reference. Could you give some help with difficulty.

**Comment by flexi-framework** [comment] 2021-03-04 15:22
Hey,
thanks for checking out Flexi. Could you provide us with more details, so that we can reproduce this issue? Helpful would be the parameter files for HOPR and the RP-Tool. Also, is there a way to provide us the mesh file, if it's not too large? Or can you reproduce this issue with a (smaller) mesh that you can comfortably share with us?
With more information, we can hopefully help you to solve this issue.

**Comment by tilokito** [comment] 2021-03-04 17:15
Yeah, for sure I can share with you the files. I would send you HOPR and prepare RP parameter files and also the output from running prepareRP code. I'm able to share with you the mesh that I'm using. However, as expected, the mesh is big enough to imposibilitate the attachment here in the github. Are there any e-mail that I can send a link sharing the files from a drive?

**Comment by flexi-framework** [comment] 2021-03-05 08:13
In order to reduce the expected amount of spam I would require you to go to our organization's website [https://www.iag.uni-stuttgart.de/en/working-groups/numerical-methods/team/](url) and send me an email to the address specified for Marius Kurz.

**Comment by flexi-framework** [comment] 2021-03-05 16:24
Hey, I just tried to reproduce the segmentation fault with your mesh and parameter files. For me everything works fine and the RPSet is produced as expected. I tested it with the current up-to-date master with the following CMake-Settings:
- GAUSS-LOBATTO
- Split_DG
- MPI
Moreover, I used the HDF5 pre-installed on the system.
Could you provide some details on your CMake-Settings and Compile Options? Did you use the up-to-date master?

**Comment by tilokito** [comment] 2021-03-05 17:01
It's weird. I'm using almost all the same configurations from CMake. To be sure that it isn't something that "broke" the code during evolution I've tried different master. The differences are that I'm using:
- FV
- BR2
- EDDYVISCOSITY
But instead of using pre-installed HDF5, I'm cloning and compiling it during the flexi compilation. Another question that may come up is that I'm using both GCC (6.x or 7.x) and Intel compilation and it's not working for both of them.

**Comment by flexi-framework** [comment] 2021-03-05 17:24
Ok. I tried those CMake settings and also used the HDF5 compiled during FLEXI compilation. It still works for me. I've used gcc 7.5. Could you maybe compile with the DEBUG compile option instead of RELEASE? This should give more details on the error and where it occurs in the system. From a short look into the code it seems to crash somewhere during the readin of the mesh, which might indicate that there is some problem with the HDF5. Other than that, you could try compiling without MPI, which would be one less source of potential errors.

**Comment by dfdeabreu** [comment] 2021-03-08 12:09
I could not perform all the tests suggested. However I notice that, when using the mesh that I provided you last week, the program was running properly. When I've tried running the code with a larger mesh, the error that I was referring occurred. I've uploaded to the drive the larger mesh, which led the code to reproduce the error.

**Comment by flexi-framework** [comment] 2021-03-08 15:36
I think I identified the issue.
**Short answer**: If you compile the code without MPI, it should produce the RPSet properly.
**Long answer**: HDF5 has a hard limit on the amount of data it can read if used with MPI. This amount is specified by a int32 counter and corresponds to about 2GB of data. To this end, a check is implemented in order to comply to that limit. For larger datasets, the behavior is undefined. It seems that this upper constraint is not computed correctly.
**However**: This check should print the following to the console if it fails:
>  _____________________________________________________________________________
> Program abort caused on Proc            0 
>   in File : src/io_hdf5/hdf5_input.f90 Line          501 
>   This file was compiled at Mar  8 2021  15:42:08
> Message: Total size of HDF5 array "SideInfo" is too big! Reduce number of entries per rank or compile without MPI!
> --------------------------------------------------------------------------
Could you please verify that you are on the up-to-date branch and this error message is written somewhere, e.g. to stderr? Since this was added to clarify the problem and the easiest solution to the used.

**Comment by dfdeabreu** [comment] 2021-04-13 21:22
I'm sorry for my late answer for the issue. I had some problems these last few days. I could once more correctly run the posti_preparerecordpoints with this advice of turning off the MPI. However it only worked when I didn't compiled with FV. I was able to run when compiled with Gauss-Lobatto + Split DG + BR2.

**Comment by flexi-framework** [comment] 2021-04-14 10:35
Hey, no problem.
There was a small bug for RP tool if compiled with FV, which was just fixed in commit a881f142 and will be available once it passes our deploy pipeline and gets pushed to GitHub (probably this afternoon/evening). In any case, the RP tool does not depend on anything FV-related, so you should thus obtain the identical RPSet regardless of compiling with or without FV.
However, it would be greatly appreciated if you could recompile and rebuilt your RPSet, once the fix is available, so we can be sure that the bug is indeed fixed.

Did I understand it correctly that by using the workaround of compiling without MPI, you were able to compuate the correct RPSet?
A real fix for the issue when compiling with MPI is currently on the way, but will need some time.

**Comment by dfdeabreu** [comment] 2021-04-14 20:20
Ok. Once the new release is available I will perform the test again to confirm if the bug is solved. Yes, I could compile and run the posti_preparerecordpoints without the MPI option and, from preliminary tests, RPSet file seems to be correct.

**Comment by flexi-framework** [comment] 2021-04-15 12:13
Great. The fix is now available on GitHub.

**Closed** 2021-04-19 08:48 UTC
